import { defineConfig, type Plugin } from "vite"
import react from "@vitejs/plugin-react"
import path from "node:path"
import fs from "node:fs"
import esbuild, { type BuildContext } from "esbuild"

function service_worker_plugin(): Plugin{
    let dev_ctx: BuildContext | null = null

    return {
        name: "service-worker-plugin",
        configureServer(server){
            server.middlewares.use(async (req, res, next) => {
                if (req.method !== "GET" && req.method !== "HEAD") return next()
                const url = new URL(req.url || "", "http://localhost")
                if (url.pathname !== "/sw.js") return next()

                try {
                    if (!dev_ctx){
                        dev_ctx = await esbuild.context({
                            entryPoints: [path.resolve(import.meta.dirname, "src/sw/main.worker.ts")],
                            bundle: true,
                            format: "esm",
                            target: "esnext",
                            write: false,
                            banner: {
                                js: "// Generated in-memory by Vite service_worker_plugin"
                            }
                        })
                    }
                    const build_result = await dev_ctx.rebuild()
                    const output = build_result.outputFiles?.[0]?.text || ""

                    res.writeHead(200, {
                        "Content-Type": "application/javascript; charset=utf-8",
                        "Cache-Control": "no-cache, no-store, must-revalidate",
                        "Service-Worker-Allowed": "/"
                    })
                    if (req.method === "HEAD"){
                        res.end()
                    }
                    else {
                        res.end(output)
                    }
                }
                catch (err){
                    console.error("[ServiceWorker Plugin] Build error in dev:", err)
                    res.writeHead(500, { "Content-Type": "text/plain; charset=utf-8" })
                    res.end(String(err))
                }
            })

            server.httpServer?.on("close", () => {
                dev_ctx?.dispose()
                dev_ctx = null
            })

            server.watcher.on("change", (file) => {
                if (file.includes("/src/sw/")){
                    server.ws.send({ type: "full-reload" })
                }
            })
        },
        async closeBundle(){
            await esbuild.build({
                entryPoints: [path.resolve(import.meta.dirname, "src/sw/main.worker.ts")],
                bundle: true,
                format: "esm",
                target: "esnext",
                outfile: path.resolve(import.meta.dirname, "dist/sw.js"),
                minify: true,
                banner: {
                    js: "// Generated by src/sw/main.worker.ts"
                }
            })
        }
    }
}

function debug_bridge_plugin(): Plugin{
    return {
        name: "debug-bridge",
        apply: "serve",
        transformIndexHtml(_html, ctx){
            return [
                {
                    tag: "script",
                    attrs: { src: "/debug_bridge.js" },
                    injectTo: "head-prepend"
                }
            ]
        },
        configureServer(server){
            const config_path = path.resolve(import.meta.dirname, ".debug/config.json")
            const template_path = path.resolve(import.meta.dirname, "cli/debug/debug_bridge_template.js")
            server.middlewares.use((req, res, next) => {
                if (req.url !== "/debug_bridge.js") return next()
                try {
                    const { port } = JSON.parse(fs.readFileSync(config_path, "utf8"))
                    const content = fs.readFileSync(template_path, "utf8").replace("{{PORT}}", String(port))
                    res.writeHead(200, { "Content-Type": "application/javascript; charset=utf-8" })
                    res.end(content)
                }
                catch {
                    res.writeHead(404)
                    res.end()
                }
            })
        }
    }
}

export default defineConfig({
    root: path.resolve(import.meta.dirname, "src/app"),
    publicDir: path.resolve(import.meta.dirname, "public"),
    plugins: [
        debug_bridge_plugin(),
        service_worker_plugin(),
        react({
            compiler: true
        }),
        {
            name: "native-entry-handler",
            configureServer(server){
                server.middlewares.use((req, _res, next) => {
                    if (req.url === "/native_entry" || req.url === "/native_entry/"){
                        req.url = "/native_entry/index.html"
                    }
                    next()
                })
            },
            closeBundle(){
                const out_dir = path.resolve(import.meta.dirname, "dist")
                const src_file = path.join(out_dir, "native_entry/index.html")
                const dest_file = path.join(out_dir, "native_entry.html")
                if (fs.existsSync(src_file)){
                    fs.copyFileSync(src_file, dest_file)
                }
            }
        }
    ],
    resolve: {
        alias: {
            "@": path.resolve(import.meta.dirname, "./src")
        }
    },
    server: {
        port: 4000,
        host: "0.0.0.0",
        fs: {
            allow: [path.resolve(import.meta.dirname)]
        }
    },
    build: {
        outDir: path.resolve(import.meta.dirname, "dist"),
        emptyOutDir: true,
        rollupOptions: {
            input: {
                main: path.resolve(import.meta.dirname, "src/app/index.html"),
                native_entry: path.resolve(import.meta.dirname, "src/app/native_entry/index.html")
            }
        }
    },
    define: {
        "process.env.NODE_ENV": JSON.stringify(process.env.NODE_ENV || "development"),
        "import.meta.env.VITE_BUILD_TIME": JSON.stringify(new Date().toUTCString()),
        "import.meta.env.VITE_NATIVE_ENTRY_URL": JSON.stringify("/")
    }
})
