// Generated by src-tauri/src/inject.ts
function e(){if(typeof window<"u"&&!window.opener){let o={postMessage:(i,t)=>{window.__TAURI__?.core?.invoke&&window.__TAURI__.core.invoke("post_message_to_main",{message:i})}};o.window=o,window.opener=o}}function n(){e()}n();
